services:
  - type: web
    name: academie-backend
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: academie-db
          property: connectionString

databases:
  - name: academie-db
